modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3"
issueTrackerURL="https://github.com/PandaDap2006/PandaLib/issues"

[[mods]]
modId = "pandalib"
version = "${version}"
displayName = "${name}"
authors = "The Panda Oliver"
logoFile = "assets/pandalib/icon.png"
description = "${description}"

[[dependencies.pandalib]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"