modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3"
issueTrackerURL="https://github.com/PandaDap2006/PandaLib/issues"
showAsResourcePack=false

[[mods]]
modId = "pandalib"
version = "${version}"
displayName = "PandaLib"
authors = "Panda Mods/The Panda Oliver"
logoFile = "icon.png"
description = "A multi purpose library with a Config API, Model and Animation API, Menu API and a bit of utility code."

[[dependencies.pandalib]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"