modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL="https://github.com/PandaDap2006/PandaLib/issues"
showAsResourcePack=false

[[mods]]
modId = "pandalib"
version = "${version}"
displayName = "PandaLib"
authors = "Panda Mods/The Panda Oliver"
logoFile = "icon.png"
description = '''
A multi purpose library with a Config API, Modal and Animation API, Menu API and a bit of utility code.
'''

[[dependencies.pandalib]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"