modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3"
issueTrackerURL="https://github.com/PandaDap2006/PandaLib/issues"
showAsResourcePack=false

[[mods]]
modId = "pandalib"
version = "${version}"
displayName = "${name}"
authors = "The Panda Oliver"
logoFile = "assets/pandalib/icon.png"
description = "${description}"

[[dependencies.pandalib]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "minecraft"
type = "required"
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "pandalib-common.mixins.json"
[[mixins]]
config = "pandalib.mixins.json"